# Generated by Django 3.2.5 on 2021-08-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210806_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Benefício', 'verbose_name_plural': 'Benefícios'},
        ),
        migrations.RenameField(
            model_name='benefit',
            old_name='criados',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='criados',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='criados',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='function',
            old_name='criados',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='criados',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='criados',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='criados',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='criados',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='criados',
            new_name='criado',
        ),
    ]
